language: python
python:
  - "3.7"
install:
  - pip3 install --upgrade pip
  - pip install coveralls
script:
  - python3 CreditCardValidatorTest.py
  - coverage run CreditCardValidatorTest.py
  - coverage report -m
after_success: coveralls
